STAYTUS_THEME: 'default'
STAYTUS_DEMO: '0'
STAYTUS_SMTP_HOSTNAME: ${MAIL_HOST}
STAYTUS_SMTP_PORT: ${MAIL_PORT}
STAYTUS_SMTP_USERNAME: ${MAIL_USERNAME}
STAYTUS_SMTP_PASSWORD: ${MAIL_PASSWORD}
FORCE_SSL: 1
